### PR TITLE
External sync

### PR DESCRIPTION
**Pull request by wtrocki**
## Motivation

Introduce decoupled fh-sync library. Remove duplicated code from module.
After merging this change all fh-sync cloud development should be done in:
https://github.com/feedhenry/fh-sync 

## Why

Introducing separate module will help us with proper documentation and building community around sync. Sync library is also decoupled from fh-mbaas express which will help us to remove any platform dependencies. Sync without mbaas-middleware can be customized. 

We need to use decoupled sync in Raincatcher to wrap it into new framework and also to introduce keycloak security mechanisms to sync. Without decoupling that work will be really difficult.

##  Side effects? 

fh-sync code was moved to separate repo without any modifications. 
All functionalities should work as they were before. 
Additional improvements can be added at later stage.

## Blockers

It will be good to review/ merge documentation and examples PR's before this one:
https://github.com/feedhenry/fh-sync/pull/7
https://github.com/feedhenry/fh-sync/pull/9

### Notes

Adding module for tests. RC1 version will be replaced with release after we will finish all tests.

@jasonmadigan  Do you think we can introduce this changes now? Any possible blockers?

Review @wei-lee @david-martin

### CODE REVIEW

**Comment by wei-lee** [comment]
Also the tests need to be fixed.

**Comment by wei-lee** [comment]
Retest this please

**Comment by wei-lee** [comment]
Looks like you need to regenerate the shrinkwrap file.

**Comment by wtrocki** [comment]
Verified with fh-js-sdk using Raincatcher.

**Comment by wei-lee** [comment]
💯 👍 good job, I say bump the version and merge it!

**Pull request merged**
