### PR TITLE
RHMAP-21086 - Upgrade fh-security to 0.4.0

### PR DESCRIPTION
**Pull request by camilamacedo86**
# JIRA:

https://issues.jboss.org/browse/RHMAP-21086

# WHAT:
* Upgrade fh-security to 0.4.0

# WHY:
* Get fixes/changes from the latest version for the next release

# HOW: 
* Run `npm install --save --save-exact <dep>@<version>`

### CODE REVIEW

**Comment by camilamacedo86** [comment]
@wei-lee could you give a hand here? It is not working with the newer version of fh-security

**Comment by wei-lee** [comment]
@camilamacedo86  is there a npm-shrinkwrap file in fh-security module? I think it's better get rid of it and try it again here.

**Comment by camilamacedo86** [comment]
@wei-lee created the PR https://github.com/feedhenry/fh-security/pull/11. We need to publish it so. Could you give a hand and verify the change?

**Comment by wei-lee** [comment]
@camilamacedo86 do you want to merge this one to #191? It should fix the problem you are having here.

**Comment by wei-lee** [comment]
replaced by #192

**Pull request closed without merging**
