### PR TITLE
remove $fh.feed

### PR DESCRIPTION
**Pull request by maleck13**
The component that $fh.feed uses has been out of action for a long time. This API is no longer documented and has not been working for a long time. So we are removing it.

@matzew FYI @PhilipGough @luigizuccarelli  review if possible please

### CODE REVIEW

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* The code changes conform to the contributing & code style guides for this component (if they exist)
* A component owner should review your change (we've tagged these above)
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* If updating server component this PR should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Ensure JIRA is up to date before & after merge (e.g. deployment notes, tester notes, release notes, fix version)
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.
Fhcap PR will be generated automatically.
To deploy your changes to a cluster place comment in this PR with pattern [x][y] where x=deploy and y=clustername you wish to deploy. 
You can also deploy your change manually using fhcap-cli

**Comment by PhilipGough** [comment]
Not much experience with this component or fh-feed but have reviewed and the changes look good to me

**Comment by wei-lee** [comment]
@maleck13 looks like the v6.0.1 is already published to npm. You should merge this PR.

**Comment by maleck13** [comment]
@wei-lee  Thanks, totally missed that

**Pull request merged**
