### PR TITLE
Removing feed API

### PR DESCRIPTION
**Pull request by matzew**
Done for [FH-2719](https://issues.jboss.org/browse/FH-2719)

@mmurphy @johnfriz  I found the above ticket on JIRA, and it seemed very reasonable to do

Wondering, since removing API - I feel version bump should be `5.14.0` ?

### CODE REVIEW

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* The code changes conform to the contributing & code style guides for this component (if they exist)
* A component owner should review your change (we've tagged these above)
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* If updating server component this PR should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Ensure JIRA is up to date before & after merge (e.g. deployment notes, tester notes, release notes, fix version)
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.
Fhcap PR will be generated automatically.
To deploy your changes to a cluster place comment in this PR with pattern [x][y] where x=deploy and y=clustername you wish to deploy. 
You can also deploy your change manually using fhcap-cli

**Comment by johnfriz** [comment]
@matzew - Since this is a breaking change to our API, it should probably be a major version bump, but don't really want to do this for a single API removal. I think we have a few other tickets knocking around from removing some other APIs. If we could bundle these together, then we could warrant a major version bump.

**Comment by matzew** [comment]
@johnfriz  - +1 on `6.0.0` bump. What tickets do you have in mind ? we can likely include them in the next sprint(s)

**Comment by johnfriz** [comment]
There are a number of APIs defined in https://github.com/feedhenry/fh-mbaas-api/blob/master/lib/api.js#L26-L50 that do not have any implementation (e.g. parse, stringify, utl) and can be removed. The "act" API has been replaced by the "service" api (they both use the same underlying implementation in act.js), so we could at least remove the definition of the "act" API. Would be good to review the others and ensure they are all documented. If not, we should either document them or remove them. We will need to announce this very prominently in out release notes for what ever release this goes out in, so people are aware of these breaking API changes.

If there are any other breaking change we are considering, I'd like to bundle them into the 6.0.0 release as well.

**Comment by matzew** [comment]
Ok, @johnfriz sounds good - I also hear 6.0.0 feature branch :-)

**Comment by matzew** [comment]
Ok, for now, we have `mbaas_6.0.0_feature` - and I will create some JIRAs out of your comments, @johnfriz

**Pull request closed without merging**
